### PR TITLE
WIP: Fix wrong specifics format and NULL amount

### PR DESCRIPTION
**Pull request by FelikZ**
Fixes CSV import with specifics and NULL amount (**WIP**)

@JC5

### CODE REVIEW

**Comment by FelikZ** [comment]
NOTE: sensitive info I have replaced with Dummy numbers in logs

1) **fixed** Parsing json file with Specifics should be an "object" not "array"
```
[2020-04-10 18:28:43] production.DEBUG: Now in Configuration::fromClassic {"file-type":"csv","date-format":"Ymd","has-headers":false,"delimiter":"tab","apply-rules":true,"specifics":{"AbnAmroDescription":1},"import-account":1,"column-count":11,"column-roles":["account-number","currency-code","date-transaction","_ignore","_ignore","_ignore","amount","description","opposing-name","opposing-iban","note"],"column-do-mapping":[true,true,false,false,false,false,false,false,true,true,false],"column-roles-complete":false,"column-mapping-config":{"0":{"888888888":5,"888888889":1,"888888899":3,"888888999":6},"1":{"EUR":1},"8":[],"9":[]}} 
[2020-04-10 18:28:43] production.DEBUG: Constructed ImportRoutineManager  
[2020-04-10 18:28:43] production.DEBUG: Going to generate identifier.  
[2020-04-10 18:28:43] production.DEBUG: Attempt #1 results in "QI2h6mJaojhLoE38"  
[2020-04-10 18:28:43] production.INFO: Job identifier is "QI2h6mJaojhLoE38"  
[2020-04-10 18:28:43] production.DEBUG: Now in startOrFindJob(QI2h6mJaojhLoE38)  
[2020-04-10 18:28:43] production.DEBUG: Try to see if file exists for job QI2h6mJaojhLoE38.  
[2020-04-10 18:28:43] production.DEBUG: File does not exist or error, create a new one.  
[2020-04-10 18:28:43] production.DEBUG: Return status. {"status":"waiting_to_start","errors":[],"warnings":[],"messages":[]} 
[2020-04-10 18:28:43] production.DEBUG: Created LineProcessor()  
[2020-04-10 18:28:43] production.DEBUG: Roles ["account-number","currency-code","date_transaction","_ignore","_ignore","_ignore","amount","description","opposing-name","opposing-iban","note"] 
[2020-04-10 18:28:43] production.DEBUG: Mapping {"0":{"888888888":5,"888888889":1,"888888899":3,"888888999":6},"1":{"EUR":1},"8":[],"9":[]} 
[2020-04-10 18:28:44] production.DEBUG: Now in App\Services\Import\ImportRoutineManager::start  
[2020-04-10 18:28:44] production.DEBUG: Now in startImportLoop()  
[2020-04-10 18:28:44] production.DEBUG: Offset is 0  
[2020-04-10 18:28:44] production.INFO: Now in App\Services\Import\Routine\CSVFileProcessor::processCSVLines with 30 records  
[2020-04-10 18:28:44] production.DEBUG: Parsing line 1/30  
[2020-04-10 18:28:44] production.ERROR: Argument 1 passed to App\Services\CSV\Specifics\SpecificService::exists() must be of the type string, int given, called in /var/www/html/app/Services/CSV/Specifics/SpecificService.php on line 82 {"exception":"[object] (TypeError(code: 0): Argument 1 passed to App\\Services\\CSV\\Specifics\\SpecificService::exists() must be of the type string, int given, called in /var/www/html/app/Services/CSV/Specifics/SpecificService.php on line 82 at /var/www/html/app/Services/CSV/Specifics/SpecificService.php:57)
[stacktrace]
#0 /var/www/html/app/Services/CSV/Specifics/SpecificService.php(82): App\\Services\\CSV\\Specifics\\SpecificService::exists(0)
#1 /var/www/html/app/Services/Import/Routine/CSVFileProcessor.php(148): App\\Services\\CSV\\Specifics\\SpecificService::runSpecifics(Array, Array)
#2 /var/www/html/app/Services/Import/Routine/CSVFileProcessor.php(105): App\\Services\\Import\\Routine\\CSVFileProcessor->processCSVLines(Object(League\\Csv\\ResultSet))
#3 /var/www/html/app/Services/Import/ImportRoutineManager.php(157): App\\Services\\Import\\Routine\\CSVFileProcessor->processCSVFile()
#4 /var/www/html/app/Console/StartImport.php(57): App\\Services\\Import\\ImportRoutineManager->start()
#5 /var/www/html/app/Console/Commands/AutoImport.php(172): App\\Console\\Commands\\AutoImport->startImport('888888999\\tEUR\\t2...', Array)
#6 /var/www/html/app/Console/Commands/AutoImport.php(190): App\\Console\\Commands\\AutoImport->importFile('all-abn.csv')
#7 /var/www/html/app/Console/Commands/AutoImport.php(92): App\\Console\\Commands\\AutoImport->importFiles(Array)
#8 [internal function]: App\\Console\\Commands\\AutoImport->handle()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array(Array, Array)
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(36): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(592): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\\Container\\Container->call(Array)
#15 /var/www/html/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#17 /var/www/html/vendor/symfony/console/Application.php(912): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#18 /var/www/html/vendor/symfony/console/Application.php(264): Symfony\\Component\\Console\\Application->doRunCommand(Object(App\\Console\\Commands\\AutoImport), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#19 /var/www/html/vendor/symfony/console/Application.php(140): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#22 /var/www/html/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#23 {main}
"} 
```
2) WIP @JC5 any ideas perhaps?
```[2020-04-10 18:18:12] production.DEBUG: Now in App\Services\Import\Routine\ColumnValueConverter::processValueArray with 4 columns in this line.  
[2020-04-10 18:18:12] production.DEBUG: getParsedValue will run CleanString  
[2020-04-10 18:18:12] production.DEBUG: Created converter class CleanString  
[2020-04-10 18:18:12] production.DEBUG: Stored column #1 with value "533333333 EUR 20200406 1234" and role "account-number" in field "source_number"  
[2020-04-10 18:18:12] production.DEBUG: getParsedValue will run CleanString  
[2020-04-10 18:18:12] production.DEBUG: Created converter class CleanString  
[2020-04-10 18:18:12] production.DEBUG: Stored column #2 with value "00 1234" and role "currency-code" in field "currency_code"  
[2020-04-10 18:18:12] production.DEBUG: getParsedValue will run Date  
[2020-04-10 18:18:12] production.DEBUG: Created converter class Date  
[2020-04-10 18:18:12] production.DEBUG: Date converter is going to work on "33 20200331 0" using format "Ymd"  
[2020-04-10 18:18:12] production.ERROR: InvalidArgumentException converting the date: Unexpected data found.
Trailing data  
[2020-04-10 18:18:12] production.DEBUG: Stored column #3 with value "2020-04-10" and role "date_transaction" in field "date"  
[2020-04-10 18:18:12] production.DEBUG: getParsedValue will run   
[2020-04-10 18:18:12] production.DEBUG: Stored column #4 with value "jc5-csv-import-v1.0.1" and role "original-source" in field "original_source"  
[2020-04-10 18:18:12] production.DEBUG: Almost final transaction {"group_title":null,"error_if_duplicate_hash":true,"transactions":[{"type":"withdrawal","date":"2020-04-10","currency_id":null,"currency_code":"00 1234","amount":null,"amount_modifier":"1","description":null,"source_id":null,"source_name":null,"destination_id":null,"destination_name":null,"tags_comma":[],"tags_space":[],"amount_debit":null,"amount_credit":null,"amount_negated":null,"source_number":"533333333 EUR 20200406 1234","original_source":"jc5-csv-import-v1.0.1"}]} 
[2020-04-10 18:18:12] production.INFO: Done parsing and combining 30 lines.  
[2020-04-10 18:18:12] production.DEBUG: Now in App\Services\Import\Routine\PseudoTransactionProcessor::processPseudo  
[2020-04-10 18:18:12] production.INFO: Converting 30 lines into transactions.  
[2020-04-10 18:18:12] production.DEBUG: Now in App\Services\Import\Routine\PseudoTransactionProcessor::processPseudoLine  
[2020-04-10 18:18:12] production.DEBUG: Now running task App\Services\Import\Task\Amount  
[2020-04-10 18:18:12] production.DEBUG: Now at the start of processAmount()  
[2020-04-10 18:18:12] production.ERROR: bcmul() expects parameter 1 to be string, null given {"exception":"[object] (TypeError(code: 0): bcmul() expects parameter 1 to be string, null given at /var/www/html/app/Services/Import/Task/Amount.php:57)
[stacktrace]
#0 /var/www/html/app/Services/Import/Task/Amount.php(57): bcmul(NULL, '1')
#1 /var/www/html/app/Services/Import/Task/Amount.php(42): App\\Services\\Import\\Task\\Amount->processAmount(Array)
#2 /var/www/html/app/Services/Import/Routine/PseudoTransactionProcessor.php(168): App\\Services\\Import\\Task\\Amount->process(Array)
#3 /var/www/html/app/Services/Import/Routine/PseudoTransactionProcessor.php(83): App\\Services\\Import\\Routine\\PseudoTransactionProcessor->processPseudoLine(0, Array)
#4 /var/www/html/app/Services/Import/ImportRoutineManager.php(167): App\\Services\\Import\\Routine\\PseudoTransactionProcessor->processPseudo(Array)
#5 /var/www/html/app/Console/StartImport.php(57): App\\Services\\Import\\ImportRoutineManager->start()
#6 /var/www/html/app/Console/Commands/AutoImport.php(172): App\\Console\\Commands\\AutoImport->startImport('888888888\\tEUR\\t2...', Array)
#7 /var/www/html/app/Console/Commands/AutoImport.php(190): App\\Console\\Commands\\AutoImport->importFile('all-abn.csv')
#8 /var/www/html/app/Console/Commands/AutoImport.php(92): App\\Console\\Commands\\AutoImport->importFiles(Array)
#9 [internal function]: App\\Console\\Commands\\AutoImport->handle()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array(Array, Array)
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(36): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(592): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\\Container\\Container->call(Array)
#16 /var/www/html/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#18 /var/www/html/vendor/symfony/console/Application.php(912): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#19 /var/www/html/vendor/symfony/console/Application.php(264): Symfony\\Component\\Console\\Application->doRunCommand(Object(App\\Console\\Commands\\AutoImport), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#20 /var/www/html/vendor/symfony/console/Application.php(140): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#23 /var/www/html/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#24 {main}
"} 
```

**Comment by JC5** [comment]
Thanks!

Please rebase this against the develop branch

**Comment by JC5** [comment]
Added some debugging for the error with amount. Thanks for showing me the logs :)

**Comment by JC5** [comment]
Build 26 is running. https://travis-ci.com/github/firefly-iii/csv-importer-docker/builds

**Comment by FelikZ** [comment]
> Please rebase this against the develop branch
+

**Comment by JC5** [comment]
Alright I dove into the code and this problem is bigger than just this line. I'm to close this PR in favor of some larger changes I have to apply to make this work.

In the new v2 config files, the specifics will no longer be [key => true] but [key, key, key] where each key is simply assumed to be true by virtue of its presence.

What you discovered is that the importer was pretty inconsistent in doing this correctly. Thanks for the PR and the fix you've suggested. I've updated the code in several places to handle this correctly.

Ironically, your new "version: 2" config files may still be using old style and thus break when you try to import. Don't use the config file, generate a new one through the importer and use that one instead.

**Comment by FelikZ** [comment]
Got it, thanks @JC5

**Pull request closed without merging**
