### PR TITLE
better date playground

### PR DESCRIPTION
**Pull request by lastlink**
fixes https://github.com/firefly-iii/firefly-iii/issues/4645

Changes in this pull request:

- better date playground for checking php dates

@JC5

### CODE REVIEW

**Comment by JC5** [comment]
I'm not going to link to w3schools, I hate those content stealing jerks. Sorry.

**Comment by lastlink** [comment]
Is there a php playground available. the other option would be to have an ajax request to validate php date formats directly within the application.

**Comment by JC5** [comment]
But that’s already in place.

**Comment by lastlink** [comment]
Where exactly? All I can tell is that there is a page with example formats, but no way to verify the formats easily within the application or another website without running your own php file to test.

I've linked issue https://github.com/firefly-iii/firefly-iii/issues/4645 for this.

**Comment by JC5** [comment]
Screenshot 2021-04-12 at 06 11 14

**Comment by lastlink** [comment]
Oh you click out for it to update. thanks!

**Pull request closed without merging**
